// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260407022957_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SupporterId")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("SupporterId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Donation", b =>
                {
                    b.Property<int>("DonationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("donation_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DonationId"));

                    b.Property<decimal?>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("amount");

                    b.Property<string>("CampaignName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("campaign_name");

                    b.Property<string>("ChannelSource")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("channel_source");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("currency_code");

                    b.Property<DateOnly>("DonationDate")
                        .HasColumnType("date")
                        .HasColumnName("donation_date");

                    b.Property<string>("DonationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("donation_type");

                    b.Property<decimal?>("EstimatedValue")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("estimated_value");

                    b.Property<string>("ImpactUnit")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("impact_unit");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("bit")
                        .HasColumnName("is_recurring");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<int?>("ReferralPostId")
                        .HasColumnType("int")
                        .HasColumnName("referral_post_id");

                    b.Property<int>("SupporterId")
                        .HasColumnType("int")
                        .HasColumnName("supporter_id");

                    b.HasKey("DonationId");

                    b.HasIndex("ReferralPostId");

                    b.HasIndex("SupporterId", "DonationDate")
                        .HasDatabaseName("ix_donations_supporter");

                    b.ToTable("donations", t =>
                        {
                            t.HasCheckConstraint("ck_donations_channel_source", "channel_source IS NULL OR channel_source IN ('Campaign','Event','Direct','SocialMedia','PartnerReferral')");

                            t.HasCheckConstraint("ck_donations_impact_unit", "impact_unit IS NULL OR impact_unit IN ('pesos','items','hours','campaigns')");

                            t.HasCheckConstraint("ck_donations_type", "donation_type IN ('Monetary','InKind','Time','Skills','SocialMedia')");
                        });
                });

            modelBuilder.Entity("Backend.Models.DonationAllocation", b =>
                {
                    b.Property<int>("AllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("allocation_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AllocationId"));

                    b.Property<DateOnly>("AllocationDate")
                        .HasColumnType("date")
                        .HasColumnName("allocation_date");

                    b.Property<string>("AllocationNotes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("allocation_notes");

                    b.Property<decimal>("AmountAllocated")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("amount_allocated");

                    b.Property<int>("DonationId")
                        .HasColumnType("int")
                        .HasColumnName("donation_id");

                    b.Property<string>("ProgramArea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("program_area");

                    b.Property<int>("SafehouseId")
                        .HasColumnType("int")
                        .HasColumnName("safehouse_id");

                    b.HasKey("AllocationId");

                    b.HasIndex("DonationId")
                        .HasDatabaseName("ix_allocations_donation");

                    b.HasIndex("SafehouseId")
                        .HasDatabaseName("ix_allocations_safehouse");

                    b.ToTable("donation_allocations", t =>
                        {
                            t.HasCheckConstraint("ck_donation_allocations_program_area", "program_area IN ('Education','Wellbeing','Operations','Transport','Maintenance','Outreach')");
                        });
                });

            modelBuilder.Entity("Backend.Models.EducationRecord", b =>
                {
                    b.Property<int>("EducationRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("education_record_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EducationRecordId"));

                    b.Property<decimal?>("AttendanceRate")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("attendance_rate");

                    b.Property<string>("CompletionStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("completion_status");

                    b.Property<string>("EducationLevel")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("education_level");

                    b.Property<string>("EnrollmentStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("enrollment_status");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<decimal?>("ProgressPercent")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("progress_percent");

                    b.Property<DateOnly>("RecordDate")
                        .HasColumnType("date")
                        .HasColumnName("record_date");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int")
                        .HasColumnName("resident_id");

                    b.Property<string>("SchoolName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("school_name");

                    b.HasKey("EducationRecordId");

                    b.HasIndex("ResidentId", "RecordDate")
                        .HasDatabaseName("ix_education_resident");

                    b.ToTable("education_records", t =>
                        {
                            t.HasCheckConstraint("ck_education_records_completion", "completion_status IS NULL OR completion_status IN ('NotStarted','InProgress','Completed')");

                            t.HasCheckConstraint("ck_education_records_level", "education_level IS NULL OR education_level IN ('Primary','Secondary','Vocational','CollegePrep')");
                        });
                });

            modelBuilder.Entity("Backend.Models.HealthWellbeingRecord", b =>
                {
                    b.Property<int>("HealthRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("health_record_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HealthRecordId"));

                    b.Property<decimal?>("Bmi")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("bmi");

                    b.Property<bool>("DentalCheckupDone")
                        .HasColumnType("bit")
                        .HasColumnName("dental_checkup_done");

                    b.Property<decimal?>("EnergyLevelScore")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("energy_level_score");

                    b.Property<decimal?>("GeneralHealthScore")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("general_health_score");

                    b.Property<decimal?>("HeightCm")
                        .HasPrecision(5, 1)
                        .HasColumnType("decimal(5,1)")
                        .HasColumnName("height_cm");

                    b.Property<bool>("MedicalCheckupDone")
                        .HasColumnType("bit")
                        .HasColumnName("medical_checkup_done");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<decimal?>("NutritionScore")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("nutrition_score");

                    b.Property<bool>("PsychologicalCheckupDone")
                        .HasColumnType("bit")
                        .HasColumnName("psychological_checkup_done");

                    b.Property<DateOnly>("RecordDate")
                        .HasColumnType("date")
                        .HasColumnName("record_date");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int")
                        .HasColumnName("resident_id");

                    b.Property<decimal?>("SleepQualityScore")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("sleep_quality_score");

                    b.Property<decimal?>("WeightKg")
                        .HasPrecision(5, 1)
                        .HasColumnType("decimal(5,1)")
                        .HasColumnName("weight_kg");

                    b.HasKey("HealthRecordId");

                    b.HasIndex("ResidentId", "RecordDate")
                        .HasDatabaseName("ix_health_resident");

                    b.ToTable("health_wellbeing_records");
                });

            modelBuilder.Entity("Backend.Models.HomeVisitation", b =>
                {
                    b.Property<int>("VisitationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("visitation_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitationId"));

                    b.Property<string>("FamilyCooperationLevel")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("family_cooperation_level");

                    b.Property<string>("FamilyMembersPresent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("family_members_present");

                    b.Property<bool>("FollowUpNeeded")
                        .HasColumnType("bit")
                        .HasColumnName("follow_up_needed");

                    b.Property<string>("FollowUpNotes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("follow_up_notes");

                    b.Property<string>("LocationVisited")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("location_visited");

                    b.Property<string>("Observations")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observations");

                    b.Property<string>("Purpose")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("purpose");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int")
                        .HasColumnName("resident_id");

                    b.Property<bool>("SafetyConcernsNoted")
                        .HasColumnType("bit")
                        .HasColumnName("safety_concerns_noted");

                    b.Property<string>("SocialWorker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("social_worker");

                    b.Property<DateOnly>("VisitDate")
                        .HasColumnType("date")
                        .HasColumnName("visit_date");

                    b.Property<string>("VisitOutcome")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("visit_outcome");

                    b.Property<string>("VisitType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("visit_type");

                    b.HasKey("VisitationId");

                    b.HasIndex("ResidentId", "VisitDate")
                        .HasDatabaseName("ix_visitations_resident");

                    b.ToTable("home_visitations", t =>
                        {
                            t.HasCheckConstraint("ck_home_visitations_cooperation", "family_cooperation_level IS NULL OR family_cooperation_level IN ('Highly Cooperative','Cooperative','Neutral','Uncooperative')");

                            t.HasCheckConstraint("ck_home_visitations_outcome", "visit_outcome IS NULL OR visit_outcome IN ('Favorable','Needs Improvement','Unfavorable','Inconclusive')");

                            t.HasCheckConstraint("ck_home_visitations_visit_type", "visit_type IN ('Initial Assessment','Routine Follow-Up','Reintegration Assessment','Post-Placement Monitoring','Emergency')");
                        });
                });

            modelBuilder.Entity("Backend.Models.InKindDonationItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<int>("DonationId")
                        .HasColumnType("int")
                        .HasColumnName("donation_id");

                    b.Property<decimal?>("EstimatedUnitValue")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("estimated_unit_value");

                    b.Property<string>("IntendedUse")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("intended_use");

                    b.Property<string>("ItemCategory")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("item_category");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("item_name");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<string>("ReceivedCondition")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("received_condition");

                    b.Property<string>("UnitOfMeasure")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("unit_of_measure");

                    b.HasKey("ItemId");

                    b.HasIndex("DonationId");

                    b.ToTable("in_kind_donation_items", t =>
                        {
                            t.HasCheckConstraint("ck_in_kind_items_category", "item_category IS NULL OR item_category IN ('Food','Supplies','Clothing','SchoolMaterials','Hygiene','Furniture','Medical')");

                            t.HasCheckConstraint("ck_in_kind_items_condition", "received_condition IS NULL OR received_condition IN ('New','Good','Fair')");

                            t.HasCheckConstraint("ck_in_kind_items_intended_use", "intended_use IS NULL OR intended_use IN ('Meals','Education','Shelter','Hygiene','Health')");

                            t.HasCheckConstraint("ck_in_kind_items_uom", "unit_of_measure IS NULL OR unit_of_measure IN ('pcs','boxes','kg','sets','packs')");
                        });
                });

            modelBuilder.Entity("Backend.Models.IncidentReport", b =>
                {
                    b.Property<int>("IncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("incident_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IncidentId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("FollowUpRequired")
                        .HasColumnType("bit")
                        .HasColumnName("follow_up_required");

                    b.Property<DateOnly>("IncidentDate")
                        .HasColumnType("date")
                        .HasColumnName("incident_date");

                    b.Property<string>("IncidentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("incident_type");

                    b.Property<string>("ReportedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reported_by");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int")
                        .HasColumnName("resident_id");

                    b.Property<DateOnly?>("ResolutionDate")
                        .HasColumnType("date")
                        .HasColumnName("resolution_date");

                    b.Property<bool>("Resolved")
                        .HasColumnType("bit")
                        .HasColumnName("resolved");

                    b.Property<string>("ResponseTaken")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_taken");

                    b.Property<int>("SafehouseId")
                        .HasColumnType("int")
                        .HasColumnName("safehouse_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("severity");

                    b.HasKey("IncidentId");

                    b.HasIndex("ResidentId");

                    b.HasIndex("SafehouseId", "IncidentDate")
                        .HasDatabaseName("ix_incidents_safehouse");

                    b.ToTable("incident_reports", t =>
                        {
                            t.HasCheckConstraint("ck_incident_reports_severity", "severity IN ('Low','Medium','High')");

                            t.HasCheckConstraint("ck_incident_reports_type", "incident_type IN ('Behavioral','Medical','Security','RunawayAttempt','SelfHarm','ConflictWithPeer','PropertyDamage')");
                        });
                });

            modelBuilder.Entity("Backend.Models.InterventionPlan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("plan_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanId"));

                    b.Property<DateOnly?>("CaseConferenceDate")
                        .HasColumnType("date")
                        .HasColumnName("case_conference_date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("PlanCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("plan_category");

                    b.Property<string>("PlanDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("plan_description");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int")
                        .HasColumnName("resident_id");

                    b.Property<string>("ServicesProvided")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("services_provided");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("status");

                    b.Property<DateOnly?>("TargetDate")
                        .HasColumnType("date")
                        .HasColumnName("target_date");

                    b.Property<decimal?>("TargetValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("target_value");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("PlanId");

                    b.HasIndex("ResidentId", "Status")
                        .HasDatabaseName("ix_interventions_resident");

                    b.ToTable("intervention_plans", t =>
                        {
                            t.HasCheckConstraint("ck_intervention_plans_category", "plan_category IN ('Safety','Psychosocial','Education','Physical Health','Legal','Reintegration')");

                            t.HasCheckConstraint("ck_intervention_plans_status", "status IN ('Open','In Progress','Achieved','On Hold','Closed')");
                        });
                });

            modelBuilder.Entity("Backend.Models.Partner", b =>
                {
                    b.Property<int>("PartnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("partner_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartnerId"));

                    b.Property<string>("ContactName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contact_name");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<string>("PartnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("partner_name");

                    b.Property<string>("PartnerType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("partner_type");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("region");

                    b.Property<string>("RoleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("role_type");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.HasKey("PartnerId");

                    b.ToTable("partners", t =>
                        {
                            t.HasCheckConstraint("ck_partners_partner_type", "partner_type IN ('Organization', 'Individual')");

                            t.HasCheckConstraint("ck_partners_role_type", "role_type IN ('Education','Evaluation','SafehouseOps','FindSafehouse','Logistics','Transport','Maintenance')");

                            t.HasCheckConstraint("ck_partners_status", "status IN ('Active', 'Inactive')");
                        });
                });

            modelBuilder.Entity("Backend.Models.PartnerAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("assignment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<DateOnly?>("AssignmentEnd")
                        .HasColumnType("date")
                        .HasColumnName("assignment_end");

                    b.Property<DateOnly>("AssignmentStart")
                        .HasColumnType("date")
                        .HasColumnName("assignment_start");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit")
                        .HasColumnName("is_primary");

                    b.Property<int>("PartnerId")
                        .HasColumnType("int")
                        .HasColumnName("partner_id");

                    b.Property<string>("ProgramArea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("program_area");

                    b.Property<string>("ResponsibilityNotes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("responsibility_notes");

                    b.Property<int?>("SafehouseId")
                        .HasColumnType("int")
                        .HasColumnName("safehouse_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.HasKey("AssignmentId");

                    b.HasIndex("PartnerId");

                    b.HasIndex("SafehouseId");

                    b.ToTable("partner_assignments", t =>
                        {
                            t.HasCheckConstraint("ck_partner_assignments_program_area", "program_area IN ('Education','Wellbeing','Operations','Transport','Maintenance')");

                            t.HasCheckConstraint("ck_partner_assignments_status", "status IN ('Active', 'Ended')");
                        });
                });

            modelBuilder.Entity("Backend.Models.ProcessRecording", b =>
                {
                    b.Property<int>("RecordingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("recording_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordingId"));

                    b.Property<bool>("ConcernsFlagged")
                        .HasColumnType("bit")
                        .HasColumnName("concerns_flagged");

                    b.Property<string>("EmotionalStateEnd")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("emotional_state_end");

                    b.Property<string>("EmotionalStateObserved")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("emotional_state_observed");

                    b.Property<string>("FollowUpActions")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("follow_up_actions");

                    b.Property<string>("InterventionsApplied")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("interventions_applied");

                    b.Property<string>("NotesRestricted")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes_restricted");

                    b.Property<bool>("ProgressNoted")
                        .HasColumnType("bit")
                        .HasColumnName("progress_noted");

                    b.Property<bool>("ReferralMade")
                        .HasColumnType("bit")
                        .HasColumnName("referral_made");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int")
                        .HasColumnName("resident_id");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("date")
                        .HasColumnName("session_date");

                    b.Property<int?>("SessionDurationMinutes")
                        .HasColumnType("int")
                        .HasColumnName("session_duration_minutes");

                    b.Property<string>("SessionNarrative")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("session_narrative");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("session_type");

                    b.Property<string>("SocialWorker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("social_worker");

                    b.HasKey("RecordingId");

                    b.HasIndex("ResidentId", "SessionDate")
                        .HasDatabaseName("ix_process_resident");

                    b.ToTable("process_recordings", t =>
                        {
                            t.HasCheckConstraint("ck_process_recordings_session_type", "session_type IN ('Individual','Group')");

                            t.HasCheckConstraint("ck_process_recordings_state_end", "emotional_state_end IS NULL OR emotional_state_end IN ('Calm','Anxious','Sad','Angry','Hopeful','Withdrawn','Happy','Distressed')");

                            t.HasCheckConstraint("ck_process_recordings_state_observed", "emotional_state_observed IS NULL OR emotional_state_observed IN ('Calm','Anxious','Sad','Angry','Hopeful','Withdrawn','Happy','Distressed')");
                        });
                });

            modelBuilder.Entity("Backend.Models.PublicImpactSnapshot", b =>
                {
                    b.Property<int>("SnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("snapshot_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SnapshotId"));

                    b.Property<string>("Headline")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("headline");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit")
                        .HasColumnName("is_published");

                    b.Property<string>("MetricPayloadJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("metric_payload_json");

                    b.Property<DateOnly?>("PublishedAt")
                        .HasColumnType("date")
                        .HasColumnName("published_at");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("date")
                        .HasColumnName("snapshot_date");

                    b.Property<string>("SummaryText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("summary_text");

                    b.HasKey("SnapshotId");

                    b.ToTable("public_impact_snapshots");
                });

            modelBuilder.Entity("Backend.Models.Resident", b =>
                {
                    b.Property<int>("ResidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("resident_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResidentId"));

                    b.Property<string>("AgeUponAdmission")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("age_upon_admission");

                    b.Property<string>("AssignedSocialWorker")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("assigned_social_worker");

                    b.Property<string>("BirthStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("birth_status");

                    b.Property<string>("CaseCategory")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("case_category");

                    b.Property<string>("CaseControlNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("case_control_no");

                    b.Property<string>("CaseStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("case_status");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CurrentRiskLevel")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("current_risk_level");

                    b.Property<DateOnly?>("DateCaseStudyPrepared")
                        .HasColumnType("date")
                        .HasColumnName("date_case_study_prepared");

                    b.Property<DateOnly?>("DateClosed")
                        .HasColumnType("date")
                        .HasColumnName("date_closed");

                    b.Property<DateOnly?>("DateColbObtained")
                        .HasColumnType("date")
                        .HasColumnName("date_colb_obtained");

                    b.Property<DateOnly?>("DateColbRegistered")
                        .HasColumnType("date")
                        .HasColumnName("date_colb_registered");

                    b.Property<DateOnly?>("DateEnrolled")
                        .HasColumnType("date")
                        .HasColumnName("date_enrolled");

                    b.Property<DateOnly?>("DateOfAdmission")
                        .HasColumnType("date")
                        .HasColumnName("date_of_admission");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<bool>("FamilyIndigenous")
                        .HasColumnType("bit")
                        .HasColumnName("family_indigenous");

                    b.Property<bool>("FamilyInformalSettler")
                        .HasColumnType("bit")
                        .HasColumnName("family_informal_settler");

                    b.Property<bool>("FamilyIs4Ps")
                        .HasColumnType("bit")
                        .HasColumnName("family_is_4ps");

                    b.Property<bool>("FamilyParentPwd")
                        .HasColumnType("bit")
                        .HasColumnName("family_parent_pwd");

                    b.Property<bool>("FamilySoloParent")
                        .HasColumnType("bit")
                        .HasColumnName("family_solo_parent");

                    b.Property<bool>("HasSpecialNeeds")
                        .HasColumnType("bit")
                        .HasColumnName("has_special_needs");

                    b.Property<string>("InitialCaseAssessment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("initial_case_assessment");

                    b.Property<string>("InitialRiskLevel")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("initial_risk_level");

                    b.Property<string>("InternalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("internal_code");

                    b.Property<bool>("IsPwd")
                        .HasColumnType("bit")
                        .HasColumnName("is_pwd");

                    b.Property<string>("LengthOfStay")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("length_of_stay");

                    b.Property<string>("NotesRestricted")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes_restricted");

                    b.Property<string>("PlaceOfBirth")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("place_of_birth");

                    b.Property<string>("PresentAge")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("present_age");

                    b.Property<string>("PwdType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pwd_type");

                    b.Property<string>("ReferralSource")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("referral_source");

                    b.Property<string>("ReferringAgencyPerson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("referring_agency_person");

                    b.Property<string>("ReintegrationStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reintegration_status");

                    b.Property<string>("ReintegrationType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reintegration_type");

                    b.Property<string>("Religion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("religion");

                    b.Property<int>("SafehouseId")
                        .HasColumnType("int")
                        .HasColumnName("safehouse_id");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .HasDefaultValue("F")
                        .HasColumnName("sex");

                    b.Property<string>("SpecialNeedsDiagnosis")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("special_needs_diagnosis");

                    b.Property<bool>("SubCatAtRisk")
                        .HasColumnType("bit")
                        .HasColumnName("sub_cat_at_risk");

                    b.Property<bool>("SubCatChildLabor")
                        .HasColumnType("bit")
                        .HasColumnName("sub_cat_child_labor");

                    b.Property<bool>("SubCatChildWithHiv")
                        .HasColumnType("bit")
                        .HasColumnName("sub_cat_child_with_hiv");

                    b.Property<bool>("SubCatCicl")
                        .HasColumnType("bit")
                        .HasColumnName("sub_cat_cicl");

                    b.Property<bool>("SubCatOrphaned")
                        .HasColumnType("bit")
                        .HasColumnName("sub_cat_orphaned");

                    b.Property<bool>("SubCatOsaec")
                        .HasColumnType("bit")
                        .HasColumnName("sub_cat_osaec");

                    b.Property<bool>("SubCatPhysicalAbuse")
                        .HasColumnType("bit")
                        .HasColumnName("sub_cat_physical_abuse");

                    b.Property<bool>("SubCatSexualAbuse")
                        .HasColumnType("bit")
                        .HasColumnName("sub_cat_sexual_abuse");

                    b.Property<bool>("SubCatStreetChild")
                        .HasColumnType("bit")
                        .HasColumnName("sub_cat_street_child");

                    b.Property<bool>("SubCatTrafficked")
                        .HasColumnType("bit")
                        .HasColumnName("sub_cat_trafficked");

                    b.HasKey("ResidentId");

                    b.HasIndex("CaseControlNo")
                        .IsUnique();

                    b.HasIndex("CaseStatus")
                        .HasDatabaseName("ix_residents_status");

                    b.HasIndex("CurrentRiskLevel")
                        .HasDatabaseName("ix_residents_risk");

                    b.HasIndex("InternalCode")
                        .IsUnique();

                    b.HasIndex("SafehouseId")
                        .HasDatabaseName("ix_residents_safehouse");

                    b.ToTable("residents", t =>
                        {
                            t.HasCheckConstraint("ck_residents_birth_status", "birth_status IS NULL OR birth_status IN ('Marital','Non-Marital')");

                            t.HasCheckConstraint("ck_residents_case_category", "case_category IS NULL OR case_category IN ('Abandoned','Foundling','Surrendered','Neglected')");

                            t.HasCheckConstraint("ck_residents_case_status", "case_status IN ('Active','Closed','Transferred')");

                            t.HasCheckConstraint("ck_residents_current_risk", "current_risk_level IS NULL OR current_risk_level IN ('Low','Medium','High','Critical')");

                            t.HasCheckConstraint("ck_residents_initial_risk", "initial_risk_level IS NULL OR initial_risk_level IN ('Low','Medium','High','Critical')");

                            t.HasCheckConstraint("ck_residents_referral_source", "referral_source IS NULL OR referral_source IN ('Government Agency','NGO','Police','Self-Referral','Community','Court Order')");

                            t.HasCheckConstraint("ck_residents_reintegration_status", "reintegration_status IS NULL OR reintegration_status IN ('Not Started','In Progress','Completed','On Hold')");

                            t.HasCheckConstraint("ck_residents_reintegration_type", "reintegration_type IS NULL OR reintegration_type IN ('Family Reunification','Foster Care','Adoption (Domestic)','Adoption (Inter-Country)','Independent Living','None')");
                        });
                });

            modelBuilder.Entity("Backend.Models.Safehouse", b =>
                {
                    b.Property<int>("SafehouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("safehouse_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SafehouseId"));

                    b.Property<int>("CapacityGirls")
                        .HasColumnType("int")
                        .HasColumnName("capacity_girls");

                    b.Property<int>("CapacityStaff")
                        .HasColumnType("int")
                        .HasColumnName("capacity_staff");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Philippines")
                        .HasColumnName("country");

                    b.Property<int>("CurrentOccupancy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("current_occupancy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("OpenDate")
                        .HasColumnType("date")
                        .HasColumnName("open_date");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("province");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("region");

                    b.Property<string>("SafehouseCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("safehouse_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.HasKey("SafehouseId");

                    b.HasIndex("SafehouseCode")
                        .IsUnique();

                    b.ToTable("safehouses", t =>
                        {
                            t.HasCheckConstraint("ck_safehouses_status", "status IN ('Active', 'Inactive')");
                        });
                });

            modelBuilder.Entity("Backend.Models.SafehouseMonthlyMetric", b =>
                {
                    b.Property<int>("MetricId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("metric_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MetricId"));

                    b.Property<int?>("ActiveResidents")
                        .HasColumnType("int")
                        .HasColumnName("active_residents");

                    b.Property<decimal?>("AvgEducationProgress")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("avg_education_progress");

                    b.Property<decimal?>("AvgHealthScore")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("avg_health_score");

                    b.Property<int?>("HomeVisitationCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("home_visitation_count");

                    b.Property<int?>("IncidentCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("incident_count");

                    b.Property<DateOnly>("MonthEnd")
                        .HasColumnType("date")
                        .HasColumnName("month_end");

                    b.Property<DateOnly>("MonthStart")
                        .HasColumnType("date")
                        .HasColumnName("month_start");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<int?>("ProcessRecordingCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("process_recording_count");

                    b.Property<int>("SafehouseId")
                        .HasColumnType("int")
                        .HasColumnName("safehouse_id");

                    b.HasKey("MetricId");

                    b.HasIndex("SafehouseId", "MonthStart")
                        .IsUnique()
                        .HasDatabaseName("ix_metrics_safehouse_month");

                    b.ToTable("safehouse_monthly_metrics");
                });

            modelBuilder.Entity("Backend.Models.SocialMediaPost", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("post_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"));

                    b.Property<int?>("AvgViewDurationSeconds")
                        .HasColumnType("int")
                        .HasColumnName("avg_view_duration_seconds");

                    b.Property<decimal?>("BoostBudgetPhp")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("boost_budget_php");

                    b.Property<string>("CallToActionType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("call_to_action_type");

                    b.Property<string>("CampaignName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("campaign_name");

                    b.Property<string>("Caption")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("caption");

                    b.Property<int?>("CaptionLength")
                        .HasColumnType("int")
                        .HasColumnName("caption_length");

                    b.Property<int?>("ClickThroughs")
                        .HasColumnType("int")
                        .HasColumnName("click_throughs");

                    b.Property<int?>("Comments")
                        .HasColumnType("int")
                        .HasColumnName("comments");

                    b.Property<string>("ContentTopic")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content_topic");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DayOfWeek")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("day_of_week");

                    b.Property<int?>("DonationReferrals")
                        .HasColumnType("int")
                        .HasColumnName("donation_referrals");

                    b.Property<decimal?>("EngagementRate")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)")
                        .HasColumnName("engagement_rate");

                    b.Property<decimal?>("EstimatedDonationValuePhp")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("estimated_donation_value_php");

                    b.Property<bool>("FeaturesResidentStory")
                        .HasColumnType("bit")
                        .HasColumnName("features_resident_story");

                    b.Property<int?>("FollowerCountAtPost")
                        .HasColumnType("int")
                        .HasColumnName("follower_count_at_post");

                    b.Property<int?>("Forwards")
                        .HasColumnType("int")
                        .HasColumnName("forwards");

                    b.Property<bool>("HasCallToAction")
                        .HasColumnType("bit")
                        .HasColumnName("has_call_to_action");

                    b.Property<string>("Hashtags")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("hashtags");

                    b.Property<int?>("Impressions")
                        .HasColumnType("int")
                        .HasColumnName("impressions");

                    b.Property<bool>("IsBoosted")
                        .HasColumnType("bit")
                        .HasColumnName("is_boosted");

                    b.Property<int?>("Likes")
                        .HasColumnType("int")
                        .HasColumnName("likes");

                    b.Property<string>("MediaType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("media_type");

                    b.Property<int?>("MentionsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("mentions_count");

                    b.Property<int?>("NumHashtags")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("num_hashtags");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("platform");

                    b.Property<string>("PlatformPostId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("platform_post_id");

                    b.Property<int?>("PostHour")
                        .HasColumnType("int")
                        .HasColumnName("post_hour");

                    b.Property<string>("PostType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("post_type");

                    b.Property<string>("PostUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("post_url");

                    b.Property<int?>("ProfileVisits")
                        .HasColumnType("int")
                        .HasColumnName("profile_visits");

                    b.Property<int?>("Reach")
                        .HasColumnType("int")
                        .HasColumnName("reach");

                    b.Property<int?>("Saves")
                        .HasColumnType("int")
                        .HasColumnName("saves");

                    b.Property<string>("SentimentTone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sentiment_tone");

                    b.Property<int?>("Shares")
                        .HasColumnType("int")
                        .HasColumnName("shares");

                    b.Property<int?>("SubscriberCountAtPost")
                        .HasColumnType("int")
                        .HasColumnName("subscriber_count_at_post");

                    b.Property<int?>("VideoViews")
                        .HasColumnType("int")
                        .HasColumnName("video_views");

                    b.Property<int?>("WatchTimeSeconds")
                        .HasColumnType("int")
                        .HasColumnName("watch_time_seconds");

                    b.HasKey("PostId");

                    b.HasIndex("Platform", "CreatedAt")
                        .HasDatabaseName("ix_posts_platform");

                    b.ToTable("social_media_posts", t =>
                        {
                            t.HasCheckConstraint("ck_social_media_posts_content_topic", "content_topic IS NULL OR content_topic IN ('Education','Health','Reintegration','DonorImpact','SafehouseLife','EventRecap','CampaignLaunch','Gratitude','AwarenessRaising')");

                            t.HasCheckConstraint("ck_social_media_posts_cta_type", "call_to_action_type IS NULL OR call_to_action_type IN ('DonateNow','LearnMore','ShareStory','SignUp')");

                            t.HasCheckConstraint("ck_social_media_posts_media_type", "media_type IS NULL OR media_type IN ('Photo','Video','Carousel','Text','Reel')");

                            t.HasCheckConstraint("ck_social_media_posts_platform", "platform IN ('Facebook','Instagram','Twitter','TikTok','LinkedIn','YouTube','WhatsApp')");

                            t.HasCheckConstraint("ck_social_media_posts_post_type", "post_type IS NULL OR post_type IN ('ImpactStory','Campaign','EventPromotion','ThankYou','EducationalContent','FundraisingAppeal')");

                            t.HasCheckConstraint("ck_social_media_posts_sentiment", "sentiment_tone IS NULL OR sentiment_tone IN ('Hopeful','Urgent','Celebratory','Informative','Grateful','Emotional')");
                        });
                });

            modelBuilder.Entity("Backend.Models.Supporter", b =>
                {
                    b.Property<int>("SupporterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("supporter_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupporterId"));

                    b.Property<string>("AcquisitionChannel")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("acquisition_channel");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<DateOnly?>("FirstDonationDate")
                        .HasColumnType("date")
                        .HasColumnName("first_donation_date");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_name");

                    b.Property<string>("OrganizationName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("organization_name");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("region");

                    b.Property<string>("RelationshipType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("relationship_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<string>("SupporterType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("supporter_type");

                    b.HasKey("SupporterId");

                    b.ToTable("supporters", t =>
                        {
                            t.HasCheckConstraint("ck_supporters_channel", "acquisition_channel IS NULL OR acquisition_channel IN ('Website','SocialMedia','Event','WordOfMouth','PartnerReferral','Church')");

                            t.HasCheckConstraint("ck_supporters_relationship", "relationship_type IS NULL OR relationship_type IN ('Local','International','PartnerOrganization')");

                            t.HasCheckConstraint("ck_supporters_status", "status IN ('Active','Inactive')");

                            t.HasCheckConstraint("ck_supporters_type", "supporter_type IN ('MonetaryDonor','InKindDonor','Volunteer','SkillsContributor','SocialMediaAdvocate','PartnerOrganization')");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Backend.Models.ApplicationUser", b =>
                {
                    b.HasOne("Backend.Models.Supporter", "Supporter")
                        .WithMany()
                        .HasForeignKey("SupporterId");

                    b.Navigation("Supporter");
                });

            modelBuilder.Entity("Backend.Models.Donation", b =>
                {
                    b.HasOne("Backend.Models.SocialMediaPost", "ReferralPost")
                        .WithMany("Donations")
                        .HasForeignKey("ReferralPostId");

                    b.HasOne("Backend.Models.Supporter", "Supporter")
                        .WithMany("Donations")
                        .HasForeignKey("SupporterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReferralPost");

                    b.Navigation("Supporter");
                });

            modelBuilder.Entity("Backend.Models.DonationAllocation", b =>
                {
                    b.HasOne("Backend.Models.Donation", "Donation")
                        .WithMany("Allocations")
                        .HasForeignKey("DonationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Safehouse", "Safehouse")
                        .WithMany("DonationAllocations")
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donation");

                    b.Navigation("Safehouse");
                });

            modelBuilder.Entity("Backend.Models.EducationRecord", b =>
                {
                    b.HasOne("Backend.Models.Resident", "Resident")
                        .WithMany("EducationRecords")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("Backend.Models.HealthWellbeingRecord", b =>
                {
                    b.HasOne("Backend.Models.Resident", "Resident")
                        .WithMany("HealthRecords")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("Backend.Models.HomeVisitation", b =>
                {
                    b.HasOne("Backend.Models.Resident", "Resident")
                        .WithMany("HomeVisitations")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("Backend.Models.InKindDonationItem", b =>
                {
                    b.HasOne("Backend.Models.Donation", "Donation")
                        .WithMany("InKindItems")
                        .HasForeignKey("DonationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donation");
                });

            modelBuilder.Entity("Backend.Models.IncidentReport", b =>
                {
                    b.HasOne("Backend.Models.Resident", "Resident")
                        .WithMany("IncidentReports")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Safehouse", "Safehouse")
                        .WithMany("IncidentReports")
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resident");

                    b.Navigation("Safehouse");
                });

            modelBuilder.Entity("Backend.Models.InterventionPlan", b =>
                {
                    b.HasOne("Backend.Models.Resident", "Resident")
                        .WithMany("InterventionPlans")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("Backend.Models.PartnerAssignment", b =>
                {
                    b.HasOne("Backend.Models.Partner", "Partner")
                        .WithMany("Assignments")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Safehouse", "Safehouse")
                        .WithMany("PartnerAssignments")
                        .HasForeignKey("SafehouseId");

                    b.Navigation("Partner");

                    b.Navigation("Safehouse");
                });

            modelBuilder.Entity("Backend.Models.ProcessRecording", b =>
                {
                    b.HasOne("Backend.Models.Resident", "Resident")
                        .WithMany("ProcessRecordings")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("Backend.Models.Resident", b =>
                {
                    b.HasOne("Backend.Models.Safehouse", "Safehouse")
                        .WithMany("Residents")
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Safehouse");
                });

            modelBuilder.Entity("Backend.Models.SafehouseMonthlyMetric", b =>
                {
                    b.HasOne("Backend.Models.Safehouse", "Safehouse")
                        .WithMany("MonthlyMetrics")
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Safehouse");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Backend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Backend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Backend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Models.Donation", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("InKindItems");
                });

            modelBuilder.Entity("Backend.Models.Partner", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("Backend.Models.Resident", b =>
                {
                    b.Navigation("EducationRecords");

                    b.Navigation("HealthRecords");

                    b.Navigation("HomeVisitations");

                    b.Navigation("IncidentReports");

                    b.Navigation("InterventionPlans");

                    b.Navigation("ProcessRecordings");
                });

            modelBuilder.Entity("Backend.Models.Safehouse", b =>
                {
                    b.Navigation("DonationAllocations");

                    b.Navigation("IncidentReports");

                    b.Navigation("MonthlyMetrics");

                    b.Navigation("PartnerAssignments");

                    b.Navigation("Residents");
                });

            modelBuilder.Entity("Backend.Models.SocialMediaPost", b =>
                {
                    b.Navigation("Donations");
                });

            modelBuilder.Entity("Backend.Models.Supporter", b =>
                {
                    b.Navigation("Donations");
                });
#pragma warning restore 612, 618
        }
    }
}
