-- ============================================================
-- SureAnchor — Azure SQL Database Schema
-- Covers all 17 CSV tables + 3 added tables for web auth/users
-- ============================================================

-- ============================================================
-- ADDED TABLES (not in the CSVs)
-- 1. AspNetUsers        — ASP.NET Identity users (staff/admin/donors)
-- 2. AspNetRoles        — RBAC roles (Admin, Staff, Donor)
-- 3. AspNetUserRoles    — Many-to-many user ↔ role mapping
-- Full ASP.NET Identity table set is generated by EF Core migrations.
-- The three tables below are the logical additions you need to know about.
-- ============================================================


-- ============================================================
-- DOMAIN 1: OPERATIONAL — Safehouses & Partners
-- ============================================================

CREATE TABLE safehouses (
    safehouse_id        INT             PRIMARY KEY,
    safehouse_code      NVARCHAR(20)    NOT NULL UNIQUE,
    name                NVARCHAR(200)   NOT NULL,
    region              NVARCHAR(100)   NOT NULL,
    city                NVARCHAR(100)   NOT NULL,
    province            NVARCHAR(100)   NOT NULL,
    country             NVARCHAR(100)   NOT NULL DEFAULT 'Philippines',
    open_date           DATE            NOT NULL,
    status              NVARCHAR(20)    NOT NULL CHECK (status IN ('Active', 'Inactive')),
    capacity_girls      INT             NOT NULL,
    capacity_staff      INT             NOT NULL,
    current_occupancy   INT             NOT NULL DEFAULT 0,
    notes               NVARCHAR(MAX)   NULL
);

CREATE TABLE partners (
    partner_id      INT             PRIMARY KEY,
    partner_name    NVARCHAR(200)   NOT NULL,
    partner_type    NVARCHAR(50)    NOT NULL CHECK (partner_type IN ('Organization', 'Individual')),
    role_type       NVARCHAR(50)    NOT NULL CHECK (role_type IN ('Education','Evaluation','SafehouseOps','FindSafehouse','Logistics','Transport','Maintenance')),
    contact_name    NVARCHAR(200)   NULL,
    email           NVARCHAR(200)   NULL,
    phone           NVARCHAR(50)    NULL,
    region          NVARCHAR(100)   NULL,
    status          NVARCHAR(20)    NOT NULL CHECK (status IN ('Active', 'Inactive')),
    start_date      DATE            NOT NULL,
    end_date        DATE            NULL,
    notes           NVARCHAR(MAX)   NULL
);

CREATE TABLE partner_assignments (
    assignment_id           INT             PRIMARY KEY,
    partner_id              INT             NOT NULL REFERENCES partners(partner_id),
    safehouse_id            INT             NULL REFERENCES safehouses(safehouse_id),
    program_area            NVARCHAR(50)    NOT NULL CHECK (program_area IN ('Education','Wellbeing','Operations','Transport','Maintenance')),
    assignment_start        DATE            NOT NULL,
    assignment_end          DATE            NULL,
    responsibility_notes    NVARCHAR(MAX)   NULL,
    is_primary              BIT             NOT NULL DEFAULT 0,
    status                  NVARCHAR(20)    NOT NULL CHECK (status IN ('Active', 'Ended'))
);


-- ============================================================
-- DOMAIN 2: CASE MANAGEMENT — Residents & Services
-- ============================================================

CREATE TABLE residents (
    resident_id                 INT             PRIMARY KEY,
    case_control_no             NVARCHAR(20)    NOT NULL UNIQUE,
    internal_code               NVARCHAR(20)    NOT NULL UNIQUE,
    safehouse_id                INT             NOT NULL REFERENCES safehouses(safehouse_id),
    case_status                 NVARCHAR(20)    NOT NULL CHECK (case_status IN ('Active','Closed','Transferred')),
    sex                         NCHAR(1)        NOT NULL DEFAULT 'F',
    date_of_birth               DATE            NULL,
    birth_status                NVARCHAR(20)    NULL CHECK (birth_status IN ('Marital','Non-Marital')),
    place_of_birth              NVARCHAR(200)   NULL,
    religion                    NVARCHAR(100)   NULL,
    case_category               NVARCHAR(50)    NULL CHECK (case_category IN ('Abandoned','Foundling','Surrendered','Neglected')),
    -- Subcategories (boolean flags)
    sub_cat_orphaned            BIT             NOT NULL DEFAULT 0,
    sub_cat_trafficked          BIT             NOT NULL DEFAULT 0,
    sub_cat_child_labor         BIT             NOT NULL DEFAULT 0,
    sub_cat_physical_abuse      BIT             NOT NULL DEFAULT 0,
    sub_cat_sexual_abuse        BIT             NOT NULL DEFAULT 0,
    sub_cat_osaec               BIT             NOT NULL DEFAULT 0,
    sub_cat_cicl                BIT             NOT NULL DEFAULT 0,
    sub_cat_at_risk             BIT             NOT NULL DEFAULT 0,
    sub_cat_street_child        BIT             NOT NULL DEFAULT 0,
    sub_cat_child_with_hiv      BIT             NOT NULL DEFAULT 0,
    -- Disability
    is_pwd                      BIT             NOT NULL DEFAULT 0,
    pwd_type                    NVARCHAR(200)   NULL,
    has_special_needs           BIT             NOT NULL DEFAULT 0,
    special_needs_diagnosis     NVARCHAR(200)   NULL,
    -- Family profile
    family_is_4ps               BIT             NOT NULL DEFAULT 0,
    family_solo_parent          BIT             NOT NULL DEFAULT 0,
    family_indigenous           BIT             NOT NULL DEFAULT 0,
    family_parent_pwd           BIT             NOT NULL DEFAULT 0,
    family_informal_settler     BIT             NOT NULL DEFAULT 0,
    -- Admission
    date_of_admission           DATE            NULL,
    age_upon_admission          NVARCHAR(50)    NULL,
    present_age                 NVARCHAR(50)    NULL,
    length_of_stay              NVARCHAR(50)    NULL,
    referral_source             NVARCHAR(100)   NULL CHECK (referral_source IN ('Government Agency','NGO','Police','Self-Referral','Community','Court Order')),
    referring_agency_person     NVARCHAR(200)   NULL,
    date_colb_registered        DATE            NULL,
    date_colb_obtained          DATE            NULL,
    assigned_social_worker      NVARCHAR(200)   NULL,
    initial_case_assessment     NVARCHAR(200)   NULL,
    date_case_study_prepared    DATE            NULL,
    -- Reintegration
    reintegration_type          NVARCHAR(100)   NULL CHECK (reintegration_type IN ('Family Reunification','Foster Care','Adoption (Domestic)','Adoption (Inter-Country)','Independent Living','None')),
    reintegration_status        NVARCHAR(50)    NULL CHECK (reintegration_status IN ('Not Started','In Progress','Completed','On Hold')),
    -- Risk
    initial_risk_level          NVARCHAR(20)    NULL CHECK (initial_risk_level IN ('Low','Medium','High','Critical')),
    current_risk_level          NVARCHAR(20)    NULL CHECK (current_risk_level IN ('Low','Medium','High','Critical')),
    -- Dates
    date_enrolled               DATE            NULL,
    date_closed                 DATE            NULL,
    created_at                  DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    notes_restricted            NVARCHAR(MAX)   NULL
);

CREATE TABLE process_recordings (
    recording_id                INT             PRIMARY KEY,
    resident_id                 INT             NOT NULL REFERENCES residents(resident_id),
    session_date                DATE            NOT NULL,
    social_worker               NVARCHAR(100)   NOT NULL,
    session_type                NVARCHAR(20)    NOT NULL CHECK (session_type IN ('Individual','Group')),
    session_duration_minutes    INT             NULL,
    emotional_state_observed    NVARCHAR(50)    NULL CHECK (emotional_state_observed IN ('Calm','Anxious','Sad','Angry','Hopeful','Withdrawn','Happy','Distressed')),
    emotional_state_end         NVARCHAR(50)    NULL CHECK (emotional_state_end IN ('Calm','Anxious','Sad','Angry','Hopeful','Withdrawn','Happy','Distressed')),
    session_narrative           NVARCHAR(MAX)   NULL,
    interventions_applied       NVARCHAR(MAX)   NULL,
    follow_up_actions           NVARCHAR(MAX)   NULL,
    progress_noted              BIT             NOT NULL DEFAULT 0,
    concerns_flagged            BIT             NOT NULL DEFAULT 0,
    referral_made               BIT             NOT NULL DEFAULT 0,
    notes_restricted            NVARCHAR(MAX)   NULL
);

CREATE TABLE home_visitations (
    visitation_id               INT             PRIMARY KEY,
    resident_id                 INT             NOT NULL REFERENCES residents(resident_id),
    visit_date                  DATE            NOT NULL,
    social_worker               NVARCHAR(100)   NOT NULL,
    visit_type                  NVARCHAR(100)   NOT NULL CHECK (visit_type IN ('Initial Assessment','Routine Follow-Up','Reintegration Assessment','Post-Placement Monitoring','Emergency')),
    location_visited            NVARCHAR(300)   NULL,
    family_members_present      NVARCHAR(300)   NULL,
    purpose                     NVARCHAR(MAX)   NULL,
    observations                NVARCHAR(MAX)   NULL,
    family_cooperation_level    NVARCHAR(50)    NULL CHECK (family_cooperation_level IN ('Highly Cooperative','Cooperative','Neutral','Uncooperative')),
    safety_concerns_noted       BIT             NOT NULL DEFAULT 0,
    follow_up_needed            BIT             NOT NULL DEFAULT 0,
    follow_up_notes             NVARCHAR(MAX)   NULL,
    visit_outcome               NVARCHAR(50)    NULL CHECK (visit_outcome IN ('Favorable','Needs Improvement','Unfavorable','Inconclusive'))
);

CREATE TABLE education_records (
    education_record_id     INT             PRIMARY KEY,
    resident_id             INT             NOT NULL REFERENCES residents(resident_id),
    record_date             DATE            NOT NULL,
    education_level         NVARCHAR(50)    NULL CHECK (education_level IN ('Primary','Secondary','Vocational','CollegePrep')),
    school_name             NVARCHAR(200)   NULL,
    enrollment_status       NVARCHAR(50)    NULL,
    attendance_rate         DECIMAL(5,4)    NULL,
    progress_percent        DECIMAL(6,2)    NULL,
    completion_status       NVARCHAR(20)    NULL CHECK (completion_status IN ('NotStarted','InProgress','Completed')),
    notes                   NVARCHAR(MAX)   NULL
);

CREATE TABLE health_wellbeing_records (
    health_record_id            INT             PRIMARY KEY,
    resident_id                 INT             NOT NULL REFERENCES residents(resident_id),
    record_date                 DATE            NOT NULL,
    general_health_score        DECIMAL(4,2)    NULL,
    nutrition_score             DECIMAL(4,2)    NULL,
    sleep_quality_score         DECIMAL(4,2)    NULL,
    energy_level_score          DECIMAL(4,2)    NULL,
    height_cm                   DECIMAL(5,1)    NULL,
    weight_kg                   DECIMAL(5,1)    NULL,
    bmi                         DECIMAL(5,2)    NULL,
    medical_checkup_done        BIT             NOT NULL DEFAULT 0,
    dental_checkup_done         BIT             NOT NULL DEFAULT 0,
    psychological_checkup_done  BIT             NOT NULL DEFAULT 0,
    notes                       NVARCHAR(MAX)   NULL
);

CREATE TABLE intervention_plans (
    plan_id                 INT             PRIMARY KEY,
    resident_id             INT             NOT NULL REFERENCES residents(resident_id),
    plan_category           NVARCHAR(50)    NOT NULL CHECK (plan_category IN ('Safety','Psychosocial','Education','Physical Health','Legal','Reintegration')),
    plan_description        NVARCHAR(MAX)   NULL,
    services_provided       NVARCHAR(MAX)   NULL,
    target_value            DECIMAL(10,2)   NULL,
    target_date             DATE            NULL,
    status                  NVARCHAR(20)    NOT NULL CHECK (status IN ('Open','In Progress','Achieved','On Hold','Closed')),
    case_conference_date    DATE            NULL,
    created_at              DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    updated_at              DATETIME2       NOT NULL DEFAULT GETUTCDATE()
);

CREATE TABLE incident_reports (
    incident_id         INT             PRIMARY KEY,
    resident_id         INT             NOT NULL REFERENCES residents(resident_id),
    safehouse_id        INT             NOT NULL REFERENCES safehouses(safehouse_id),
    incident_date       DATE            NOT NULL,
    incident_type       NVARCHAR(50)    NOT NULL CHECK (incident_type IN ('Behavioral','Medical','Security','RunawayAttempt','SelfHarm','ConflictWithPeer','PropertyDamage')),
    severity            NVARCHAR(20)    NOT NULL CHECK (severity IN ('Low','Medium','High')),
    description         NVARCHAR(MAX)   NULL,
    response_taken      NVARCHAR(MAX)   NULL,
    resolved            BIT             NOT NULL DEFAULT 0,
    resolution_date     DATE            NULL,
    reported_by         NVARCHAR(100)   NULL,
    follow_up_required  BIT             NOT NULL DEFAULT 0
);

CREATE TABLE safehouse_monthly_metrics (
    metric_id                   INT             PRIMARY KEY,
    safehouse_id                INT             NOT NULL REFERENCES safehouses(safehouse_id),
    month_start                 DATE            NOT NULL,
    month_end                   DATE            NOT NULL,
    active_residents            INT             NULL,
    avg_education_progress      DECIMAL(6,2)    NULL,
    avg_health_score            DECIMAL(4,2)    NULL,
    process_recording_count     INT             NULL DEFAULT 0,
    home_visitation_count       INT             NULL DEFAULT 0,
    incident_count              INT             NULL DEFAULT 0,
    notes                       NVARCHAR(MAX)   NULL,
    UNIQUE (safehouse_id, month_start)
);


-- ============================================================
-- DOMAIN 3: DONOR & SUPPORT
-- ============================================================

CREATE TABLE supporters (
    supporter_id        INT             PRIMARY KEY,
    supporter_type      NVARCHAR(50)    NOT NULL CHECK (supporter_type IN ('MonetaryDonor','InKindDonor','Volunteer','SkillsContributor','SocialMediaAdvocate','PartnerOrganization')),
    display_name        NVARCHAR(200)   NOT NULL,
    organization_name   NVARCHAR(200)   NULL,
    first_name          NVARCHAR(100)   NULL,
    last_name           NVARCHAR(100)   NULL,
    relationship_type   NVARCHAR(50)    NULL CHECK (relationship_type IN ('Local','International','PartnerOrganization')),
    region              NVARCHAR(100)   NULL,
    country             NVARCHAR(100)   NULL,
    email               NVARCHAR(200)   NULL,
    phone               NVARCHAR(50)    NULL,
    status              NVARCHAR(20)    NOT NULL CHECK (status IN ('Active','Inactive')),
    created_at          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    first_donation_date DATE            NULL,
    acquisition_channel NVARCHAR(50)    NULL CHECK (acquisition_channel IN ('Website','SocialMedia','Event','WordOfMouth','PartnerReferral','Church'))
);

CREATE TABLE social_media_posts (
    post_id                         INT             PRIMARY KEY,
    platform                        NVARCHAR(50)    NOT NULL CHECK (platform IN ('Facebook','Instagram','Twitter','TikTok','LinkedIn','YouTube','WhatsApp')),
    platform_post_id                NVARCHAR(100)   NULL,
    post_url                        NVARCHAR(500)   NULL,
    created_at                      DATETIME2       NOT NULL,
    day_of_week                     NVARCHAR(20)    NULL,
    post_hour                       INT             NULL,
    post_type                       NVARCHAR(50)    NULL CHECK (post_type IN ('ImpactStory','Campaign','EventPromotion','ThankYou','EducationalContent','FundraisingAppeal')),
    media_type                      NVARCHAR(30)    NULL CHECK (media_type IN ('Photo','Video','Carousel','Text','Reel')),
    caption                         NVARCHAR(MAX)   NULL,
    hashtags                        NVARCHAR(MAX)   NULL,
    num_hashtags                    INT             NULL DEFAULT 0,
    mentions_count                  INT             NULL DEFAULT 0,
    has_call_to_action              BIT             NOT NULL DEFAULT 0,
    call_to_action_type             NVARCHAR(50)    NULL CHECK (call_to_action_type IN ('DonateNow','LearnMore','ShareStory','SignUp')),
    content_topic                   NVARCHAR(100)   NULL CHECK (content_topic IN ('Education','Health','Reintegration','DonorImpact','SafehouseLife','EventRecap','CampaignLaunch','Gratitude','AwarenessRaising')),
    sentiment_tone                  NVARCHAR(50)    NULL CHECK (sentiment_tone IN ('Hopeful','Urgent','Celebratory','Informative','Grateful','Emotional')),
    caption_length                  INT             NULL,
    features_resident_story         BIT             NOT NULL DEFAULT 0,
    campaign_name                   NVARCHAR(200)   NULL,
    is_boosted                      BIT             NOT NULL DEFAULT 0,
    boost_budget_php                DECIMAL(12,2)   NULL,
    impressions                     INT             NULL,
    reach                           INT             NULL,
    likes                           INT             NULL,
    comments                        INT             NULL,
    shares                          INT             NULL,
    saves                           INT             NULL,
    click_throughs                  INT             NULL,
    video_views                     INT             NULL,
    engagement_rate                 DECIMAL(8,4)    NULL,
    profile_visits                  INT             NULL,
    donation_referrals              INT             NULL,
    estimated_donation_value_php    DECIMAL(14,2)   NULL,
    follower_count_at_post          INT             NULL,
    watch_time_seconds              INT             NULL,
    avg_view_duration_seconds       INT             NULL,
    subscriber_count_at_post        INT             NULL,
    forwards                        INT             NULL
);

CREATE TABLE donations (
    donation_id         INT             PRIMARY KEY,
    supporter_id        INT             NOT NULL REFERENCES supporters(supporter_id),
    donation_type       NVARCHAR(50)    NOT NULL CHECK (donation_type IN ('Monetary','InKind','Time','Skills','SocialMedia')),
    donation_date       DATE            NOT NULL,
    is_recurring        BIT             NOT NULL DEFAULT 0,
    campaign_name       NVARCHAR(200)   NULL,
    channel_source      NVARCHAR(50)    NULL CHECK (channel_source IN ('Campaign','Event','Direct','SocialMedia','PartnerReferral')),
    currency_code       NVARCHAR(10)    NULL,
    amount              DECIMAL(14,2)   NULL,
    estimated_value     DECIMAL(14,2)   NULL,
    impact_unit         NVARCHAR(50)    NULL CHECK (impact_unit IN ('pesos','items','hours','campaigns')),
    notes               NVARCHAR(MAX)   NULL,
    referral_post_id    INT             NULL REFERENCES social_media_posts(post_id)
);

CREATE TABLE in_kind_donation_items (
    item_id                 INT             PRIMARY KEY,
    donation_id             INT             NOT NULL REFERENCES donations(donation_id),
    item_name               NVARCHAR(200)   NOT NULL,
    item_category           NVARCHAR(50)    NULL CHECK (item_category IN ('Food','Supplies','Clothing','SchoolMaterials','Hygiene','Furniture','Medical')),
    quantity                INT             NULL,
    unit_of_measure         NVARCHAR(20)    NULL CHECK (unit_of_measure IN ('pcs','boxes','kg','sets','packs')),
    estimated_unit_value    DECIMAL(12,2)   NULL,
    intended_use            NVARCHAR(50)    NULL CHECK (intended_use IN ('Meals','Education','Shelter','Hygiene','Health')),
    received_condition      NVARCHAR(20)    NULL CHECK (received_condition IN ('New','Good','Fair'))
);

CREATE TABLE donation_allocations (
    allocation_id       INT             PRIMARY KEY,
    donation_id         INT             NOT NULL REFERENCES donations(donation_id),
    safehouse_id        INT             NOT NULL REFERENCES safehouses(safehouse_id),
    program_area        NVARCHAR(50)    NOT NULL CHECK (program_area IN ('Education','Wellbeing','Operations','Transport','Maintenance','Outreach')),
    amount_allocated    DECIMAL(14,2)   NOT NULL,
    allocation_date     DATE            NOT NULL,
    allocation_notes    NVARCHAR(MAX)   NULL
);


-- ============================================================
-- DOMAIN 4: OUTREACH
-- ============================================================

CREATE TABLE public_impact_snapshots (
    snapshot_id         INT             PRIMARY KEY,
    snapshot_date       DATE            NOT NULL,
    headline            NVARCHAR(500)   NULL,
    summary_text        NVARCHAR(MAX)   NULL,
    metric_payload_json NVARCHAR(MAX)   NULL,
    is_published        BIT             NOT NULL DEFAULT 0,
    published_at        DATE            NULL
);


-- ============================================================
-- ADDED TABLE 1: AspNetUsers (ASP.NET Identity — generated by EF Core)
-- Shown here for documentation. Do NOT run manually;
-- use: dotnet ef database update
-- Key fields added beyond Identity defaults:
--   supporter_id  → links an authenticated donor to their supporter record
--   display_name  → shown in UI
-- ============================================================

-- CREATE TABLE AspNetUsers (
--     Id                  NVARCHAR(450)   PRIMARY KEY,
--     UserName            NVARCHAR(256)   NULL,
--     NormalizedUserName  NVARCHAR(256)   NULL,
--     Email               NVARCHAR(256)   NULL,
--     NormalizedEmail     NVARCHAR(256)   NULL,
--     EmailConfirmed      BIT             NOT NULL,
--     PasswordHash        NVARCHAR(MAX)   NULL,
--     SecurityStamp       NVARCHAR(MAX)   NULL,
--     ConcurrencyStamp    NVARCHAR(MAX)   NULL,
--     PhoneNumber         NVARCHAR(MAX)   NULL,
--     PhoneNumberConfirmed BIT            NOT NULL,
--     TwoFactorEnabled    BIT             NOT NULL,
--     LockoutEnd          DATETIMEOFFSET  NULL,
--     LockoutEnabled      BIT             NOT NULL,
--     AccessFailedCount   INT             NOT NULL,
--     -- Custom fields:
--     supporter_id        INT             NULL REFERENCES supporters(supporter_id),
--     display_name        NVARCHAR(200)   NULL
-- );

-- ============================================================
-- ADDED TABLE 2: AspNetRoles  (Admin, Staff, Donor)
-- ADDED TABLE 3: AspNetUserRoles (many-to-many)
-- Both generated by EF Core migrations automatically.
-- Roles to seed: Admin, Staff, Donor
-- ============================================================


-- ============================================================
-- INDEXES for common query patterns
-- ============================================================

CREATE INDEX ix_residents_safehouse     ON residents(safehouse_id);
CREATE INDEX ix_residents_status        ON residents(case_status);
CREATE INDEX ix_residents_risk          ON residents(current_risk_level);
CREATE INDEX ix_process_resident        ON process_recordings(resident_id, session_date);
CREATE INDEX ix_visitations_resident    ON home_visitations(resident_id, visit_date);
CREATE INDEX ix_education_resident      ON education_records(resident_id, record_date);
CREATE INDEX ix_health_resident         ON health_wellbeing_records(resident_id, record_date);
CREATE INDEX ix_interventions_resident  ON intervention_plans(resident_id, status);
CREATE INDEX ix_incidents_safehouse     ON incident_reports(safehouse_id, incident_date);
CREATE INDEX ix_donations_supporter     ON donations(supporter_id, donation_date);
CREATE INDEX ix_allocations_donation    ON donation_allocations(donation_id);
CREATE INDEX ix_allocations_safehouse   ON donation_allocations(safehouse_id);
CREATE INDEX ix_posts_platform          ON social_media_posts(platform, created_at);
CREATE INDEX ix_metrics_safehouse_month ON safehouse_monthly_metrics(safehouse_id, month_start);
